In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_rows', None)#使其显示完全

In [12]:
#获取数据集

data=pd.read_csv(r"C:\Users\ZHUO\Desktop\start_to_stop.csv")
data.shape #(4547,185) 原来是189列 后去掉时间三列和event_id

(4547, 185)

In [13]:
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4547 entries, 0 to 4546
Columns: 185 entries, rest_time to avg_temp_mode
dtypes: float64(139), int64(46)
memory usage: 6.4 MB


rest_time  heart_rate_stop  heart_rate_start  time_elapsed  \
0          0            132.0              71.0           153   
1         50            156.0              82.0          1318   
2          0            156.0              64.0           152   
3         12            166.0             116.0          1643   
4          0            138.0              72.0           425   

   total_running_time  time_since_last_stop  time_from_start_to_stop  \
0                 153                   NaN                      153   
1                1318                1318.0                     1115   
2                 152                   NaN                      152   
3                1643                1643.0                     1479   
4                 425                   NaN                      425   

   altitude_start  distance_start  speed_start  cadence_start  altitude_stop  \
0           193.4         0.00062       5.5764             59          184.0   
1           178.6         0.55216       0.0000              0          199.6   
2           181.6         0.00036       3.1572              0          204.4   
3           209.8         0.50847       0.1692              0          215.6   
4           229.4         0.00000       2.9232             55          173.0   

   distance_stop  speed_stop  cadence_stop  altitude_change_past_60_seconds  \
0        0.55201     10.5156            76                             13.8   
1        4.83519     12.9672            81                             13.2   
2        0.50820     11.7216            82                             14.8   
3        5.98351     10.9512            81                             22.2   
4        1.44891     13.3020            83                              2.2   

   altitude_change_past_120_seconds  altitude_change_past_180_seconds  \
0                              -9.0                              -9.4   
1                              20.2                              20.8   
2                             -22.0                              22.8   
3                              26.4                              36.2   
4                              -2.2                              -2.6   

   altitude_change_past_240_seconds  altitude_change_past_300_seconds  \
0                              -9.4                              -9.4   
1                              23.6                              29.8   
2                              22.8                              22.8   
3                              31.2                              30.2   
4                              -1.2                             -25.6   

   altitude_change_past_360_seconds  altitude_change_past_420_seconds  \
0                              -9.4                              -9.4   
1                              31.8                              21.0   
2                              22.8                              22.8   
3                              30.0                              30.4   
4                              15.2                             -55.8   

   altitude_change_past_480_seconds  altitude_change_past_540_seconds  \
0                              -9.4                              -9.4   
1                              14.4                              29.4   
2                              22.8                              22.8   
3                              23.8                              28.4   
4                             -56.4                             -56.4   

   altitude_change_past_600_seconds  altitude_change_past_660_seconds  \
0                              -9.4                              -9.4   
1                              30.2                              25.4   
2                              22.8                              22.8   
3                              29.0                              31.6   
4                             -56.4                             -56.4   

   altitude_change_past_720_

In [7]:
#计算每一列NaN的占比
data.isnull().sum().sort_values(ascending=False)/data.shape[0]

heart_rate_past_10800_to_14400_seconds                  0.262811
heart_rate_past_14400_seconds                           0.262811
heart_rate_past_10800_seconds                           0.262811
heart_rate_past_7200_seconds                            0.262811
heart_rate_past_3600_to_7200_seconds                    0.262811
heart_rate_past_7200_to_10800_seconds                   0.262811
heart_rate_past_1800_to_3600_seconds                    0.246316
heart_rate_past_3600_seconds                            0.246316
heart_rate_past_900_to_1800_seconds                     0.199032
heart_rate_past_1800_seconds                            0.199032
time_since_last_stop                                    0.182098
heart_rate_past_840_to_900_seconds                      0.137233
heart_rate_past_900_seconds                             0.137233
heart_rate_past_780_to_840_seconds                      0.132615
heart_rate_past_840_seconds                             0.132615
heart_rate_past_720_to_78

In [14]:
data.isnull().sum()/data.shape[0]

rest_time                                               0.000000
heart_rate_stop                                         0.018034
heart_rate_start                                        0.035848
time_elapsed                                            0.000000
total_running_time                                      0.000000
time_since_last_stop                                    0.182098
time_from_start_to_stop                                 0.000000
altitude_start                                          0.000000
distance_start                                          0.000000
speed_start                                             0.000000
cadence_start                                           0.000000
altitude_stop                                           0.000000
distance_stop                                           0.000000
speed_stop                                              0.000000
cadence_stop                                            0.000000
altitude_change_past_60_s

In [7]:
#统计数据集中有哪些列包含NaN
data_nan=[]

for col in data.columns:
    if data[col].isnull().sum()>0:
        data_nan.append(col)
        
len(data_nan)

48

In [8]:
#针对空缺值的处理方式
#折中法：对于数值列类型 取中位数；对于分类列，取NaN

for col in data_nan:
    data[col].fillna(data[col].median(),inplace=True)#中位数代替

data.shape

(4547, 185)

In [9]:
data.to_csv('dataset.csv')

In [8]:
#方差过滤
from sklearn.feature_selection import VarianceThreshold
X=data
selector=VarianceThreshold()
X_fsvar=selector.fit_transform(X)
X_fsvar.shape

(4547, 185)

In [9]:
X['altitude_change_past_10800_to_14400_seconds'].var()

2.294933640732007

In [10]:
#新增一列作为标签
data['heart_rate_change_value']=data["heart_rate_stop"]-data["heart_rate_start"]
data.shape

(4547, 186)

In [11]:
data.head()

rest_time  heart_rate_stop  heart_rate_start  time_elapsed  \
0          0            132.0              71.0           153   
1         50            156.0              82.0          1318   
2          0            156.0              64.0           152   
3         12            166.0             116.0          1643   
4          0            138.0              72.0           425   

   total_running_time  time_since_last_stop  time_from_start_to_stop  \
0                 153                   NaN                      153   
1                1318                1318.0                     1115   
2                 152                   NaN                      152   
3                1643                1643.0                     1479   
4                 425                   NaN                      425   

   altitude_start  distance_start  speed_start  ...  avg_temp2  avg_temp_mean  \
0           193.4         0.00062       5.5764  ...        NaN            NaN   
1           178.6         0.55216       0.0000  ...        NaN            NaN   
2           181.6         0.00036       3.1572  ...        NaN            NaN   
3           209.8         0.50847       0.1692  ...        NaN            NaN   
4           229.4         0.00000       2.9232  ...        NaN            NaN   

     avg_lat   avg_long     avg_alt      avg_hr  avg_speed  total_dist  \
0  41.966027 -87.646939  178.671811  145.828347  13.563011     4.83519   
1  41.966027 -87.646939  178.671811  145.828347  13.563011     4.83519   
2  41.975176 -87.650256  192.049602  155.442131  13.040247     5.98351   
3  41.975176 -87.650256  192.049602  155.442131  13.040247     5.98351   
4  41.964429 -87.642942  178.924319  156.492138  13.428711    14.54317   

   avg_temp_mode  heart_rate_change_value  
0            NaN                     61.0  
1            NaN                     74.0  
2            NaN                     92.0  
3            NaN                     50.0  
4            NaN                     66.0  

[5 rows x 186 columns]

In [12]:
#归一化
from sklearn.preprocessing import MinMaxScaler
x=data.drop(columns=['heart_rate_change_value'],axis=1).values
scaler = MinMaxScaler()  #实例化
X= scaler.fit_transform(x)
print(X)

t=data['heart_rate_change_value'].values.reshape(-1,1) #转换成一列
y=scaler.fit_transform(t)
print(y)

[[0.         0.42458101 0.15       ... 0.31471346 0.10899549        nan]
 [0.01200768 0.55865922 0.205      ... 0.31471346 0.10899549        nan]
 [0.         0.55865922 0.115      ... 0.27466667 0.13612588        nan]
 ...
 [0.00144092 0.60335196 0.555      ... 0.25731945 0.33746019 0.75806452]
 [0.36263208 0.60893855 0.13       ... 0.25731945 0.33746019 0.75806452]
 [0.00600384 0.55307263 0.4        ... 0.25731945 0.33746019 0.75806452]]
[[0.58498024]
 [0.63636364]
 [0.70750988]
 ...
 [0.39130435]
 [0.7312253 ]
 [0.47826087]]


In [13]:
#数据集分离
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=10)

In [14]:
#将X_train和y_train合并
xt=pd.DataFrame(X_train)
yt=pd.DataFrame(y_train)
xt.columns=data.columns[:-1]
yt.columns=['heart_rate_change_value']
xyt=pd.concat((xt,yt),axis=1)
xyt.head()
xyt.shape

xyt.to_csv('train.csv')  #3182

In [15]:
xt=pd.DataFrame(X_train)
xt.head()

0         1      2         3         4         5         6    \
0  0.000000  0.586592  0.150  0.011415  0.011415       NaN  0.011415   
1  0.021614  0.223464  0.465  0.058189  0.056588  0.047849  0.003341   
2  0.002642  0.592179  0.470  0.099603  0.096680  0.164782  0.072040   
3  0.000720  0.452514  0.520  0.155495  0.149231  0.202703  0.022064   
4  0.012968  0.636872  0.200  0.108095  0.090903  0.130723  0.006891   

        7         8         9    ...       175       176       177       178  \
0  0.531499  0.000000  0.202312  ...  0.800000  0.806452  0.789631  0.734097   
1  0.496353  0.073158  0.349470  ...  0.916667  0.919355  0.915345  0.735361   
2  0.565650  0.043598  0.149446  ...  0.583333  0.596774  0.560446  0.735529   
3  0.503647  0.207981  0.339355  ...  0.633333  0.645161  0.597356  0.734828   
4  0.528183  0.113962  0.165222  ...  0.350000  0.370968  0.296575  0.736166   

        179       180       181       182       183       184  
0  0.003288  0.648744  0.484522  0.241328  0.309353  0.806452  
1  0.003270  0.650670  0.665217  0.213962  0.134174  0.935484  
2  0.003270  0.666284  0.646265  0.350605  0.124125  0.596774  
3  0.003279  0.604050  0.563850  0.251099  0.189119  0.645161  
4  0.003266  0.649857  0.348246  0.100705  0.160134  0.370968  

[5 rows x 185 columns]

In [47]:
#将X_test和y_test合并
xe=pd.DataFrame(X_test)
ye=pd.DataFrame(y_test)
xe.columns=data.columns[:-1]
ye.columns=['heart_rate_change_value']
xye=pd.concat((xe,ye),axis=1)
xye.head()
xye.shape

xye.to_csv('test.csv')

(1365, 186)

In [44]:
#未经归一化后的数据集分离
from sklearn.model_selection import train_test_split
X_train1,X_test1,y_train1,y_test1=train_test_split(x,t,test_size=0.3,random_state=10)

In [56]:
#将X_train1和y_train1合并
xt1=pd.DataFrame(X_train1)
yt1=pd.DataFrame(y_train1)
xt1.columns=data.columns[:-1]
yt1.columns=['heart_rate_change_value']

xyt1=pd.concat((xt1,yt1),axis=1)
xyt1.shape

xyt1.to_csv('train1.csv')

In [58]:
#将X_test1和y_test1合并
xe1=pd.DataFrame(X_test1)
ye1=pd.DataFrame(y_test1)
xe1.columns=data.columns[:-1]
ye1.columns=['heart_rate_change_value']
xye1=pd.concat((xe1,ye1),axis=1)
xye1.head()
xye1.shape

xye1.to_csv('test1.csv')

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
df=pd.read_csv(r"C:\Users\ZHUO\Desktop\train1.csv",index_col=0)
df.head()

rest_time  heart_rate_stop  heart_rate_start  time_elapsed  \
0        0.0            161.0              71.0         164.0   
1       90.0             96.0             134.0         836.0   
2       11.0            162.0             135.0        1431.0   
3        3.0            137.0             145.0        2234.0   
4       54.0            170.0              81.0        1553.0   

   total_running_time  time_since_last_stop  time_from_start_to_stop  \
0               164.0                 710.0                    164.0   
1               813.0                 352.0                     48.0   
2              1389.0                1200.0                   1035.0   
3              2144.0                1475.0                    317.0   
4              1306.0                 953.0                     99.0   

   altitude_start  distance_start  speed_start  ...  avg_temp2  avg_temp_mean  \
0           178.2         0.00000       6.0480  ...       23.0      23.510820   
1           157.0         2.32925      10.4472  ...       30.0      30.193087   
2           198.8         1.38810       4.4676  ...       10.0      11.328488   
3           161.4         6.62182      10.1448  ...       13.0      13.290435   
4           176.2         3.62841       4.9392  ...       -4.0      -2.697563   

     avg_lat   avg_long     avg_alt      avg_hr  avg_speed  total_dist  \
0  41.951512 -87.643213  174.734274  143.381054  12.605056    13.31553   
1  41.963483 -87.647441  175.247647  154.753239  12.247823     5.90091   
2  41.965081 -87.647290  179.409400  153.560481  14.031540     5.47555   
3  41.958440 -87.645287  162.821807  148.373588  12.732593     8.22650   
4  41.971107 -87.648315  175.031021  134.804395  10.769385     6.99967   

   avg_temp_mode  heart_rate_change_value  
0           23.0                     90.0  
1           31.0                    -38.0  
2           10.0                     27.0  
3           13.0                     -8.0  
4           -4.0                     89.0  

[5 rows x 186 columns]

In [10]:
pd.set_option('display.max_columns', None)#使其显示完全
df.columns

Index(['rest_time', 'heart_rate_stop', 'heart_rate_start', 'time_elapsed',
       'total_running_time', 'time_since_last_stop', 'time_from_start_to_stop',
       'altitude_start', 'distance_start', 'speed_start',
       ...
       'avg_temp2', 'avg_temp_mean', 'avg_lat', 'avg_long', 'avg_alt',
       'avg_hr', 'avg_speed', 'total_dist', 'avg_temp_mode',
       'heart_rate_change_value'],
      dtype='object', length=186)

In [9]:
df.columns

Index(['rest_time', 'heart_rate_stop', 'heart_rate_start', 'time_elapsed',
       'total_running_time', 'time_since_last_stop', 'time_from_start_to_stop',
       'altitude_start', 'distance_start', 'speed_start',
       ...
       'avg_temp2', 'avg_temp_mean', 'avg_lat', 'avg_long', 'avg_alt',
       'avg_hr', 'avg_speed', 'total_dist', 'avg_temp_mode',
       'heart_rate_change_value'],
      dtype='object', length=186)

In [16]:
#将25个特征提取出来成为一个新的dataframe
df2=df[['rest_time'
              ,'heart_rate_stop'
              ,'heart_rate_start'
              ,'time_elapsed'
              ,'total_running_time'
              ,'time_since_last_stop'
              ,'time_from_start_to_stop'
              ,'altitude_start'                              
              ,'distance_start'
              ,'speed_start'
              ,'cadence_start'
              ,'altitude_stop'
              ,'distance_stop'                                           
              ,'speed_stop'                                             
              ,'cadence_stop'
              ,'avg_temp'                                              
              ,'avg_temp2'                                              
              ,'avg_temp_mean'                                           
              ,'avg_lat'                                                
              ,'avg_long'                                                
              ,'avg_alt'                                                 
              ,'avg_hr'                                                  
              ,'avg_speed'                                               
              ,'total_dist'                                              
              ,'avg_temp_mode']]


In [17]:
df2.head()

rest_time  heart_rate_stop  heart_rate_start  time_elapsed  \
0        0.0            161.0              71.0         164.0   
1       90.0             96.0             134.0         836.0   
2       11.0            162.0             135.0        1431.0   
3        3.0            137.0             145.0        2234.0   
4       54.0            170.0              81.0        1553.0   

   total_running_time  time_since_last_stop  time_from_start_to_stop  \
0               164.0                 710.0                    164.0   
1               813.0                 352.0                     48.0   
2              1389.0                1200.0                   1035.0   
3              2144.0                1475.0                    317.0   
4              1306.0                 953.0                     99.0   

   altitude_start  distance_start  speed_start  cadence_start  altitude_stop  \
0           178.2         0.00000       6.0480           55.0          187.0   
1           157.0         2.32925      10.4472           80.0          173.8   
2           198.8         1.38810       4.4676            0.0          194.6   
3           161.4         6.62182      10.1448           82.0          156.6   
4           176.2         3.62841       4.9392            0.0          184.4   

   distance_stop  speed_stop  cadence_stop  avg_temp  avg_temp2  \
0        0.55700     12.1248          82.0      23.0       23.0   
1        2.34087      0.0684           0.0      30.0       30.0   
2        5.47555     15.0804          84.0      10.0       10.0   
3        7.68637     11.6568          81.0      13.0       13.0   
4        3.90232      9.2052          85.0      -4.0       -4.0   

   avg_temp_mean    avg_lat   avg_long     avg_alt      avg_hr  avg_speed  \
0      23.510820  41.951512 -87.643213  174.734274  143.381054  12.605056   
1      30.193087  41.963483 -87.647441  175.247647  154.753239  12.247823   
2      11.328488  41.965081 -87.647290  179.409400  153.560481  14.031540   
3      13.290435  41.958440 -87.645287  162.821807  148.373588  12.732593   
4      -2.697563  41.971107 -87.648315  175.031021  134.804395  10.769385   

   total_dist  avg_temp_mode  
0    13.31553           23.0  
1     5.90091           31.0  
2     5.47555           10.0  
3     8.22650           13.0  
4     6.99967           -4.0

In [18]:
df2.shape

(3182, 25)